ogging.level.org.hibernate.SQL: debug            # ?? ???? ?? ????
spring.jpa.properties.hibernate.format_sql: true  # ??? ??? ?? ?? ??
spring.jpa.hibernate.ddl-auto: create             # ?? ??? ??? ??, ?? DB?? ?? ???? ? ?

#create : ?? ??? ?? ??? ??
#create-drop : ?? ??? ?? ??? ??, ?? ??? ??? ??
#update : ?? ??? ??? ?? ??. ???? ??? ??
#validate : ?? ??? ???? ??? ??, ??? ??
#none : ?? ???? ??