spring:
  profiles:
    active: local
  batch:
    jdbc:
      initialize-schema: always
  h2:
    console:
      enabled: true
      path: /h2

---

spring:
  config:
    activate:
      on_profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:test
      driver-class-name: org.h2.Driver
      username: sa
      password:
  batch:
    jdbc:
      initialize-schema: embedded
    job:
      enabled: false  #Job이 자동으로 실행되지 않도록 설정, JobRunner에서 실행 되도록

---

spring:
  config:
    activate:
      on_profile: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
